rafaelfajardo/border-games-rewrite

public/crosser.js

of the original. This queue has all the sprites added, and a time
interval is used to step between the rendering of each sprite, which
can be configured. In addition, a few properties are added to the
sprites, including a name (for logging purposes), a speed of movement
(so we know how far to move), and a direction (generally 'right' or
'left').

Added a rendering queue for handling the sprite-by-sprite rendering

---

public/controller.js

resolve #2 place updateStatus(pad) in its own .js file

---

public/index.html
public/main.js

remove controller code updateStatus(pad) and keyTyped() functions from main.js.
add reference to controller.js to index.html
remove reference to about.js from index.html

remove controller code from main.js file, update index.html for controller.js

---

README.md
public/controller.js

worked on updateStatus(pad) function, commenting out code that would make it more complicated. we may wish to delete that commented code as cruft at a future time.
worked on keyTyped() function, adding comments to help reveal intent. I realize that this function may break because it acts on a set of Boolean variables defined in main.js or crosser.js. I've noted this in the comments to that function.

worked on updateStatus(pad) function and comments on keyTyped() function

---

Crosser-positions-turns-travel.txt
LaMigra-postitions-turns-travel.txt

added two documents, one each for Crosser and La Migra positions turn order and distance travelled

adding documents with initial positions and distance travelled

---

public/crosser.js

Work In Progress (WIP) reordering of sprite creation to match turns, and correction of initial positions.

WIP reorder of sprite loading and positions

---

public/crosser.js

Merging in changes to player behavior, so it's now bounded, and correct wrapping around the screen.

Render queue

---

public/lamigra.js

trying to figure out an error in the preload() function. This is the first time I'm trying to use "let" instead of "var" and I may have the scope wrong.

edit preload(), still getting errors

---

public/lamigra.js

I had used "+" when I meant to multiply.

fixed typo in position of deportationcenter and avisocounter

---

public/crosser.js

gato2.speed is now 32*2 and matches the others on its row.

fixed gato2.speed which was too fast

---

public/lamigra.js

added the debug flags to lamigra.js within the preload()
removed the debug flag from setup()

have added the remainder of the debug flags

---

public/controller.js

Trying to clean up cruft in controller.js

Cleaned up comments and commented out touch UI

---

public/index.html

added code to index.html to test CSS styling for buttons created by Form element.
This is Player GUI work in progress

added embedded CSS style to form buttons

---

public/crosser.js

edited crosser.js var BUGGY, set flag to false, to check the visual effects of recent changes.

edited var BUGGY,set it to false, to check visual

---

public/ui/ui.js

fixed unbalanced parenthesis in line 60 of ui.js

fixed unbalanced parenthesis in line ui.js:60

---

public/ui/ui.js

these are small changes to keyReleased() in public/ui/ui.js to attempt to get it to launch/open a webpage from within the sketch. no success so far. tried httpGet() and loadJSON().

several changes to ui/ui.js

---

public/ui/controller.js
public/ui/ui.js

was -- finally -- able to use a line of code to invoke/launch a url/webpage. This was attached to keyReleased() p5.js code as a test. was successful and so then copied the code snippet to public/ui/controller.js. was able to get "select" and "start" buttons on controller to launch the desired target webpages within the desired _self window.
ToDo: get the code for a single button push on the controller. the controller is polled too many rapidly and so a single button push is read as many button pushes. this is also necessary for gameplay.

invoked window html5 element in public/ui/ui.js

---

public/ui/controller.js

added html5/javascript code snippets to public/ui/controller.js:
ongamepadconnected()
ongamepaddisconnected()
these may be used to communicate the state of the hardware in gallery environment, or they may be deleted later as cruft.

added html5 code snippets to public/ui/controller.js, may delete later

---

public/ui/ui.js

in public/ui/ui.js
added two error messages to draw() to warn if no controller is connected, and if the wrong browser is being used. These rely on Javascript.

testing two error messages to console to validate environment

---

public/ui/controller.js

added state change statements to gamepad buttons 12-15 within public/ui/controller.js 
may promote these changes later

added statements to pad buttons 12-15 in public/ui/controller.js

---

public/crosser.js

added a Boolean variable called moveIdle and defaults to true so we can represent an idle state for the player character.

added boolean variable moveIdle default to true so player can be idle

---

public/crosser.js

deleted remaining references to sprite velocities in crosser.js draw(). These were in the if() statements that responded to player-character movement and in the test for overlap with visa sprite. this is cruft cleanup.

deleted deprecated code that assigned velocities in crosser.js, draw(),

---

public/_crosser.html
public/_lamigra.html
public/index.html
public/installationStyle.css

deprecated html <form> based UI which requires a mouse-press in favor of JS window element which can be triggered by a JS event. moved CSS from index.html to its own file so it can be referenced by all HTML files. Added <div> elements to HTML and CSS files. 
The language in the content and the positioning in the <div> is a work in progress.

deprecated form ui, moved css to external file, implemented <div>

---

public/crosser.js
public/lamigra.js

cut:
CSS from index.html
created and pasted CSS into:
installationStyle.css
so all three HTML files can reference it.
deprecated HTML form element in favor of JS window element to call games into _self browser window. this was experiment in /public/ui/ui.js which will be promoted to main.js Work In Progress
copied snippet of code from main.js that uses P5JS DOM reference to position canvas within a parent HTML <div> element from within the sketch. this is in the setup() and replaces the createCanvas() syntax with a var assigned to contain the canvas which can then be assigned a parent.
added:
rough draft of credit  and instructions text to left <div>. The contents are still a Work In Progress. Visual styling of text, backgrounds, etc, are still a Work In Progress.

made changes to HTML, CSS, and setup() in _crosser.js and _lamigra.js

---

public/_crosser.html
public/_lamigra.html
public/index.html

I can't believe this was so difficult to find!!!! FUCK!!!!
rather than add some kind of alignment directive within the cascading style sheet to center the contents of a div, which should have been simple but has taken me a month to figure out, one has to place an align = "center" attribute in the div tag invocation in the html file. okay, that little stylistic thing is now taken care of.

added align attribute to div tag centering canvas in apprpriate div

---

public/main.js

added a browser vendor test to send a message to console if not Google Chrome browser. This was tested in the /public/ui subdirectory and code was copied and pasted from ui.js in that location.

added browser vendor test to main.js draw loop

---

public/main.js

copied global variable declaration for top-level User Interface from 
/public/ui/ui.js for button sprites, image placeholders, and counter into
/public/main.js
this is a step toward moving experiments from /ui/ui.js into master branch

copied variables for top UI from /public/ui/ui.js into /public/main.js

---

about.txt
public/controller.js
public/crosser.js
public/lamigra.js
public/main.js

updated about.txt with news about Ars Electronica and updated UI needs from DAM. Will have to look into Leap Motion Controller for 2021 03 target date at DAM. Ars Electronica would like to be online 2020 08 15. Will only need keyboard+mouse for that date.

update about.txt with summary of offline developments from last month

---

package.json
public/crosser.js
public/lamigra.js

have changed / corrected the URLs in package.json to reflect the renaming of the repo.
added variable declarations to top of crosser.js and lamigra.js to begin refining keyboard input

change package.json to reflect repo rename, refine keyboard input in progress commit

---

public/crosser.js

tried several steps to refine how carlosmoreno sprite behaves. he is pushed onto the renderQueue when he is created, but the keyTyped() function and the draw() function give him precedence. It may be just as well so a contemporary player doesn't get frustrated. I have added an 'idle' state to both the above functions and to the updateSprite(sprite) function which will be needed for La Migra

refining how carlosmoreno behaves

---

public/_crosser.html
public/_lamigra.html
public/lamigra.js

resolve #1 
added keyTyped() to La Migra
added state variables to be affected by keyboard input
added if-then state machine to draw() to test for state variable
fixed assignment instead of evaluation in state machine in draw()
migra now moves left and right from keyboard input. can also be mapped to controller input and touch input in the future.

added functionality to La Migra so player character moves

---

public/lamigra.js

resolve #42 
added code to create a Group() of sprites in draw loop called cuffs
cuffs launch from front of migra and head up and are removed at the border, the limits of their jurisdiction.
new issue, they move too fast. will likely be resolved when we implement renderQueue Chris created for Crosser. can then push each one onto the renderQueue as it's created.

added to La Migra, esposas/cuffs. can use Group() from Play !objects

---

public/main.js

commented out console.log('warning, no gamepads connected');
will be useful to bring back later under installation conditions after authoring and editing for Leap Motion Controller

commented out console.log('warning, no gamepads connected');

---

public/controller.js

cleaned up white space in keyTyped() in controller.js for readability

cleaned up white space in keyTyped() for readability

---

public/crosser.js

resolves #126 
resolves #127 
commented out the code that was the first draft state machine for movement for carlosmoreno in draw() in crosser.js
this allowed the keyTyped() function to change his state in the updateSprite() and honor the renderQueue[] order and timings.
it also required a conditional test at the bottom of draw() that returns carlosmoreno to idle state if not keyIsPressed each frame. 
this means that carlosmoreno now takes his turn in the renderQueue and the player has to button mash to get him to move. This closer approximates the original.

commented out carlosmoreno movement states & added idle state in draw()

---

public/crosser.js

will be used by gameState = 'select"

added variables for ui buttons to crosser.js

---

public/lamigra.js

should give option for gameState = 'select' UI
may need to fold actions from keyReleased() function into keyTyped() function and deprecate the former across all js files.

added code for UI select buttons and keyReleased() in lamigra.js

---

public/_crosser.html
public/_lamigra.html
public/crosser.js
public/index.html
public/lamigra.js

added placeholder code into draw() for game manager state machine in crosser.js and lamigra.js
added link to gitHub repository declaring we are open source into index.html, _crosser.html, and _lamigra.html

added placeholder game manager state machine and a link to source

---

public/_crosser.html
public/_lamigra.html
public/index.html
public/main.js

added "noopener noreferrer" attribute to links to gitHub in html files
added code to implement mouse click in main.js it's not yet working

added a measure of security for html links, added code for mouse click 

---

public/main.js

added a visual test to see if mouseClicked() is registering. It is, but is not launching new window.

mouseClicked() buttons still not working

---

public/_crosser.html
public/_lamigra.html
public/index.html

added meta tag with charset utf-8 declaration to index, crosser, and lamigra html files

added charset="utf-8" declaration to the html files

---

about.txt

harmonizing about txt file in working branch with main branch. it's confusing to me otherwise.

harmonizing about text in ars branch with main branch

---

public/_crosser.html
public/_lamigra.html
public/index.html

added a paragraph to the left column of each html file acknowledging that the games are currently a work in progress of rewriting.

added Work In Progress paragraph to html files.

---

public/lamigra.js

added an if-statement to checkForPeanutSprite() to see if I can test for collision detection in this function. Also added a comment to help remember to preserve a line that works that is encapsulated by the new if-statemetn.

Testing collision detection in checkForPeanutSprite()

---

about.txt

added note to about.txt

---

public/_crosser.html
public/_lamigra.html
public/index.html

moved instructions to left column. propagated credits in right column.

updated text in 3 html files more appropriate for installation

---

public/crosser.js

comment specifying which function ( updateRendering() ) calls this function ( updateSprite() )

added clarifying comment to updateSprite()

---

public/crosser.js

added comment to head of updateRendering() to clarify that it is called by/from the draw() loop and that it -- in turn -- calls upon updateSprite() and stopSprite().

added clarifying comments to updateRendering()

---

about.txt

added note in about.txt signaling the new issues defined/declared on gitHub. These issues begin to detail the collision detections needed for lamigra.js. The issues are a kind of game design document for meaning bearing collisions/overlaps.

added note about new issues defined for lamigra.js on gitHub.

---

public/crosser.js

Adjusted collision boxes so that they don't overlap, this branch fixes that and moves most of them into the right spot. Also separated out the debug drawing of sprites with another variable named 'DRAW_COLLIDER', which will get set to true automatically if BUGGY is set to true. Finally, renamed inputDelay to INPUT_DELAY to make it clear it's a constant, not a variable to be changed.

Collisions

---

public/crosser.js
public/main.js

1 fixed a bug I introduced to main.js when I copied and pasted gamepad code from crosser.js. This pasted code invoked a sprite (carlosmoreno) that does not exist in main.js. This has been fixed.
2 some long-ago deprecated state variables that had been commented out of crosser.js but which remained in place have been deleted from that file to make reading code easier. this was cruft control.

two changes: 1 bug fix to main.js gamepad code; 2 delete deprecated code from crosser.js

---

public/crosser.js

made NPC collision boxes smaller so that there are safe-zone rows to be able to time the next move. It is still difficult but may now be winnable.

adjusted collision boxes to the NPCs making them smaller.

---

public/main.js

commented out long-deprecated state variable in main.js

---

public/main.js

deleted long-deprecated code that invoked a state variable that was itself deprecated long ago. Cruft control.

deleted deprecated code from main.js keyTyped();

---

public/main.js

commented out keyCodes in keyTyped() for arrow keys that never worked in main.js

---

public/main.js

deleted deprecated keyCodes in keyTyped() from main.js

---

public/crosser.js

freeware font and license available at http://www.04.jp.org/
I have included a zip archive with source and license in ../dependencies as well.

cite source of font in comment in crosser.js

---

public/lamigra.js

moving things don't run into each other. This has the problem that
the sprites have colliders which are too big, so they can't overlap.
In essence, everything stays 1 space away.

Added a group called solids (which could be renamed, haha) so that

---

public/lamigra.js

reset the total timeout to 2 mins

reduced overall timeout to 2 mins

---

public/lamigra.js

This just adds text rendering, which has to happen after draw sprites, to the draw loop of the game. This should be fixed up to be nice.

added basic instructions to starting, needs to be fixed up

---

public/crosser.js
public/lamigra.js
public/main.js

This changes the way the controller is read to be more universal with most game pads in Chrome on Windows. Unfortunately this causes some issues with Chrome on Mac which seems to be inconsistent in behavior (Firefox tends to work better for controllers on Mac)

Controller fixes
