rafaelfajardo/border-games-rewrite

public/crosser.js
in crosser.js I have adjusted the preload() function so as to: have the creation order reflect the turn order of the sprites in the render queue; correct the initial positions of the sprites to reflect the 2000 version; and, set the speed variable to reflect the distance traveled per turn in the 2000 version. 
There is one caveat. I have left carlosmoreno at (or near) the top of the preload function because in the original it was possible for a non-player character to travel over the player character. Play's render queue has the newer sprite on top of the older sprite. We can assess this choice for game feel down the road.
=> adjusted initial positions, turn order, and distance traveled (speed)

public/crosser.js, public/lamigra.js
Work in progress, add code to set debug flags in lamigra.js
will help to see bounding boxes for collision detection
trying to see if it works when sprites are declared and initialized in preload()
already know it works in setup()
reordered the debug flags in crosser.js to reflect the turn order
=> WIP set debug flags in lamigra.js

public/controller.js
edited touchStarted() in controller.js to comment out the function which will not be needed for exhibition. May revisit in the future. 
Also, the "return" at the bottom of this same function was throwing an error. This is strange because p5js had said to include it to prevent another error. This was left in place but also commented out as a single line to revisit if needed.
=> "return" at bottom of touchStarted() throwing an error. commented out.

public/ui/ui.js
corrected sprite names for buttons in keyReleased() function. had automatically started with btn0, but had declared no such variable. instead declared btn1 and btn2. correction now reflects declared variable names.
=> corrected sprite names in keyReleased()

public/crosser.js
deleted a chunk of code in setup() that created velocities for each non-player-character sprite in crosser.js. this code was superseded by the render queue. this is cruft cleanup.
=> deleted deprecated code that refers to velocity in crosser.js

public/crosser.js
deleted code that had been commented out within draw(), within crosser.js, within collision test between carlosmoreno player character and any member of group lamigra which had changed velocities of lamigra to 0. we no longer refer to nor assign velocities to the sprites. this is cruft cleanup.
=> deleted deprecated code in draw() re velocity change on overlap()

public/crosser.js
deleted commented-out code from crosser.js that was my first attempt to create a render queue using an element that was inside the play.p5.js library. this is cruft cleanup.
=> deleted commented-out code that was my first attempt at a render queue

public/crosser.js, public/touch.js
removed deprecated code from preload() that had created a touch sprite with SNES controller art. moved that code as a comment to the end of touch.js since it has useful solutions for positioning art.
=> removed deprecated code from preload(). moved comment to end of touch.js

public/crosser.js
deleted deprecated code in preload that had created a set of static images for the sprite carlosmoreno which we don't use anywhere. these had been commented out for quite a while. this is cruft cleanup.
=> deleted deprecated code in preload() for carlosmoreno

public/index.html
added comment to index.html explaining that the align = "center" attribute is deprecated in html5 in favor of pushing it to CSS.
https://www.geeksforgeeks.org/html-div-align-attribute/
http://w3schools-fa.ir/tags/att_div_align.html
however I was unable to find a CSS solution, so I have used the deprecated syntax which still works in the version of Chrome I am developing on.
=> added a comment to the index.html

public/installationStyle.css
tweaked colors for background #4d4d4d (~30% lightness) and text #cccccc (~80% lightness). This for the "frame" around the games expressed by html files. CSS still has colored borders around divs which are meant to go away as soon as I feel the content is in the right places.
=> tweaked colors in CSS closer to desired grays for background and text

public/installationStyle.css
edited CSS to make borders around divs disappear by making them 0 pixels wide. This makes it easier to evaluate the visual aesthetic.
=> edit CSS to make borders = 0px wide

public/main.js
added a console message in main.js that appears when no gamepads are connected. May be handy, may be cruft.
=> added console warning when no gamepads connected to main.js

public/crosser.js, public/lamigra.js
last commit added a redundant declaration of ctr0 at global scope. this crashed everything. I've commented out the older version and so now it works again
=> fixed redundant var ctr0 declaration

public/crosser.js
when I first drafted the rewriting of crosser I thought we would need a different boolean flag for each key stroke to signal the intended direction of movement. 
This would allow for, afford the opportunity for, two keys pressed to signal a diagonal movement intent. I am realizing that the movements for carlosmoreno in crosser.js are mutually exclusive and limited to the cardinal directions. It may be possible to do the same thing with a string variable and tests for up, down, left, right, and idle strings.
=> moved chunk declaring movement variables up in crosser.js, may deprecate later

public/lamigra.js
changed code for keyReleased() in lamigra.js to invoke index.html when "g" key is released, this can also be mapped to the Select key on the SNES controller. This should be simpler than trying to invoke a transparent UI "scene" that will overlay the game in this window.
=> changed code for keyReleased() in lamigra.js to invoke index.html

public/crosser.js
changing keyReleased() code in crosser.js to invoke index.html when "g" key is pressed. This simplifies and resolves need for Select UI layer overlay in crosser.js. It will also reload the _crosser.html url when the "h" key is pressed. Both of these can be mapped to a controller, Select and Start button.
=> changed code in keyReleased() for crosser.js to invoke index.html

public/_crosser.html, public/_lamigra.html, public/index.html
there were images, clickable buttons, in the left and right columns of the html documents. These depend on the presence of a mouse for mouse clicks. Mice won't be part of the DAM installation and so I've deprecated these bits by commenting them out.
=> deprecated mouse click links with image in 3 html documents

public/main.js
we are no longer designing for the iBuffalo SNES controller. It has hardware turbo feature that we cannot control in an installation. We are now designing for a generic NES controller.
=> commented out iBuffalo SNES specific code in updateStatus(pad); for main.js

public/lamigra.js
cruft control. deleted code that attempted to replicate main.js within lamigra.js which had been deprecated and commented out. it now invokes the URL for index.html which is just as effective.
=> deleted deprecated UI code in keyReleased() from lamigra.js

public/lamigra.js
cruft control. keyCodes for arrow keys were deleted because they never worked, and tests for "t", "y", "g", and "h" were deleted as well; all within keyTyped() within lamigra.js
=> deleted deprecated keyCodes and keys in keyTyped() for lamigra.js

public/lamigra.js
fixing an error I had introduced. forgot to put quotation marks around 'rectangle' in collision box declaration for sprites.
=> fixed punctuation error in collision box definition for cacahuates
